from logging import exception


s=-1
if s<0:


         raise exception('the mean is')